"""add core platform services tables

Revision ID: 2aa35684f8e3
Revises: 1745a724ab1d
Create Date: 2026-08-06 14:25:16.162269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '2aa35684f8e3'
down_revision: Union[str, Sequence[str], None] = '1745a724ab1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_event_type'), 'activity_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_request_id'), 'activity_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_source'), 'activity_logs', ['source'], unique=False)
    op.create_table('memory_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_records_category'), 'memory_records', ['category'], unique=False)
    op.create_index(op.f('ix_memory_records_created_at'), 'memory_records', ['created_at'], unique=False)
    op.create_table('tool_execution_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('is_success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Float(), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_execution_logs_created_at'), 'tool_execution_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_tool_execution_logs_request_id'), 'tool_execution_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_tool_execution_logs_tool_name'), 'tool_execution_logs', ['tool_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_execution_logs_tool_name'), table_name='tool_execution_logs')
    op.drop_index(op.f('ix_tool_execution_logs_request_id'), table_name='tool_execution_logs')
    op.drop_index(op.f('ix_tool_execution_logs_created_at'), table_name='tool_execution_logs')
    op.drop_table('tool_execution_logs')
    op.drop_index(op.f('ix_memory_records_created_at'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_category'), table_name='memory_records')
    op.drop_table('memory_records')
    op.drop_index(op.f('ix_activity_logs_source'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_request_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_event_type'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
