"""add engineering approval fields

Revision ID: 5087f9b244fd
Revises: 8f1d9d4b2c11
Create Date: 2026-08-13 03:41:35.802209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5087f9b244fd'
down_revision: Union[str, Sequence[str], None] = '8f1d9d4b2c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_runs', sa.Column('engineering_approved_by', sa.String(length=100), nullable=True))
    op.add_column('workflow_runs', sa.Column('engineering_approved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_runs', 'engineering_approved_at')
    op.drop_column('workflow_runs', 'engineering_approved_by')
    # ### end Alembic commands ###
