"""add_intake_sessions_table

Revision ID: 576b184229c1
Revises: 4444cde0d494
Create Date: 2026-08-07 15:18:03.988510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '576b184229c1'
down_revision: Union[str, Sequence[str], None] = '4444cde0d494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intake_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('specification', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intake_sessions_created_at'), 'intake_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_intake_sessions_owner_id'), 'intake_sessions', ['owner_id'], unique=False)
    op.create_index(op.f('ix_intake_sessions_status'), 'intake_sessions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intake_sessions_status'), table_name='intake_sessions')
    op.drop_index(op.f('ix_intake_sessions_owner_id'), table_name='intake_sessions')
    op.drop_index(op.f('ix_intake_sessions_created_at'), table_name='intake_sessions')
    op.drop_table('intake_sessions')
    # ### end Alembic commands ###
