import re
from typing import Optional
import uuid
from sqlalchemy.ext.asyncio import AsyncSession

from app.schemas.agent import AgentExecutionRequest, AgentExecutionResponse, DisciplineRole
from app.schemas.model_router import Capability
from app.services.agents.base import BaseAgent


class ChallengerAgent(BaseAgent):

    def __init__(self, db: AsyncSession):
        super().__init__(
            role=DisciplineRole.REVIEWER,
            capability=Capability.CHALLENGE,
            db=db,
        )

    def get_system_prompt(self) -> str:
        return (
            "You are the Challenger/Verifier for the Shipyard Engineering Organization.\n"
            "Your mission is to perform automated contract and quality checks on outputs generated by other primary agents.\n"
            "You must ensure the output (found in primary_output in context) adheres to the structural formats, contains all required XML tags, and addresses the task specification.\n\n"
            "Output constraints:\n"
            "You must evaluate the output and output a status tag on a separate line at the end:\n"
            "- If all criteria are met: <challenge status=\"passed\"></challenge>\n"
            "- If there are issues, gaps, or malformed tags: <challenge status=\"failed\" reason=\"detailed explanation of what is wrong and how to fix it\"></challenge>\n"
            "Be strict and precise. If the output fails, provide actionable feedback in the reason attribute."
        )

    async def run_challenge(
        self,
        step_name: str,
        primary_output: str,
        specification_ref: Optional[uuid.UUID] = None,
        model_override: Optional[str] = None,
        primary_model: Optional[str] = None,
        request_id: Optional[str] = None,
    ) -> AgentExecutionResponse:
        task_input = (
            f"Please verify the output of the '{step_name}' agent.\n"
            f"Step-specific Verification Requirements:\n"
        )
        if step_name == "coordinator_planning":
            task_input += "- Output must be a valid markdown document outlining a build plan."
        elif step_name == "architect_designing":
            task_input += "- Output must contain a valid Mermaid diagram enclosed in <diagram>```mermaid ... ```</diagram> tags.\n- Output must contain one or more ADR sections enclosed in <adr id=\"...\"> ... </adr> tags."
        elif step_name == "builder_building":
            task_input += "- Output must contain one or more file implementations enclosed in <file path=\"...\"> ... </file> tags.\n- Output must contain test results enclosed in <test_results> ... </test_results> tags."
        elif step_name == "reviewer_reviewing":
            task_input += "- Output must contain the review status tag in the format: <review status=\"approved\"></review> or <review status=\"request_changes\" reason=\"...\"></review>."
        elif step_name == "qa_testing":
            task_input += "- Output must contain the QA status tag in the format: <qa_status>PASSED</qa_status> or <qa_status>FAILED</qa_status>."
        else:
            task_input += "- Output must be structured and address the specification."

        context = {
            "primary_output": primary_output
        }
        if model_override:
            context["model_override"] = model_override

        req = AgentExecutionRequest(
            task_input=task_input,
            specification_ref=specification_ref,
            context=context,
        )

        response = await self.run(req, request_id)
        if response.status == "success":
            content = response.output_text
            from app.utils.tag_parser import parse_agent_decision
            
            result = parse_agent_decision(content, "challenge")
            status = result.get("status")
            reason = result.get("reason")
            
            if status:
                status = status.lower()
                if status not in ["passed", "failed"]:
                    status = "failed"
                    reason = f"Invalid challenge status '{status}' returned by verifier."
            else:
                # Default to fail-closed on parsing failure
                status = "failed"
                reason = "Challenger verification tag/JSON was missing or malformed."
            
            response.artifacts = {
                "challenge_status": status,
                "challenge_reason": reason if reason else "No details provided."
            }
            if primary_model and request_id:
                primary_capability = {
                    "coordinator_planning": Capability.GENERAL_REASONING,
                    "architect_designing": Capability.ARCHITECTURE,
                    "builder_building": Capability.CODING,
                    "reviewer_reviewing": Capability.CODE_REVIEW,
                    "qa_testing": Capability.TESTING,
                    "platform_reporting": Capability.GENERAL_REASONING,
                }.get(step_name, Capability.GENERAL_REASONING)
                await self.model_router.record_quality_feedback(
                    request_id,
                    primary_model,
                    primary_capability,
                    1.0 if status == "passed" else 0.0,
                )
        return response
